<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TF-D116" failures="0" tests="5" name="TestNG.DataProviderEx" time="0.002" errors="1" timestamp="2023-02-23T14:42:20 IST" skipped="0">
  <testcase classname="TestNG.DataProviderEx" name="validateProducts" time="0.000"/>
  <system-out/>
  <testcase classname="TestNG.DataProviderEx" name="validateProducts" time="0.000"/>
  <system-out/>
  <testcase classname="TestNG.DataProviderEx" name="validateProducts" time="0.000"/>
  <system-out/>
  <testcase classname="TestNG.DataProviderEx" name="validateProducts" time="0.002"/>
  <system-out/>
  <testcase classname="TestNG.DataProviderEx" name="myTest" time="0.000">
    <error message="
Method public void TestNG.DataProviderEx.myTest(java.lang.String) requires a @DataProvider named : data" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Method public void TestNG.DataProviderEx.myTest(java.lang.String) requires a @DataProvider named : data
at org.testng.internal.Parameters.findDataProvider(Parameters.java:561)
at org.testng.internal.Parameters.handleParameters(Parameters.java:772)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:791)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </error>
  </testcase> <!-- myTest -->
  <system-out/>
</testsuite> <!-- TestNG.DataProviderEx -->
